version: "3.8"

services:
  web_app:
    build: .
    cap_drop:
      - ALL
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      RUST_LOG: info
      OPENTELEMETRY_IP: jaeger
    security_opt:
      - no-new-privileges:true
    pid: "service:jaeger"
    networks:
      - bingokta
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      # kics-scan ignore-line
      test: ["NONE"]

  jaeger:
    image: jaegertracing/all-in-one:latest
    cap_drop:
      - ALL
    ports:
      - "127.0.0.1:16686:16686"
      - "0.0.0.0:55681:55681"
    environment:
      COLLECTOR_OTLP_ENABLED: true
      COLLECTOR_OTLP_HTTP_HOST_PORT: 55681
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    security_opt:
      - no-new-privileges:true
    pid: "service:web_app"
    networks:
      - bingokta
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "http://jaeger:16686",
          "-O",
          "/dev/null",
        ]
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  bingokta:
    driver: bridge
