version: "3.8"

services:
  bingokta:
    build: .
    ports:
      - 8080:8080
    environment:
      RUST_LOG: debug
      OPENTELEMETRY_IP: jeager

  jaeger:
    hostname: jeager
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 55681:55681
    environment:
      COLLECTOR_OTLP_ENABLED: true
      COLLECTOR_OTLP_HTTP_HOST_PORT: 55681
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
