version: "3.8"

services:
  web_app:
    build: .
    cap_drop:
      - ALL
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      RUST_LOG: info
      OPENTELEMETRY_IP: jaeger
    security_opt:
      - no-new-privileges:true
    # kics-scan ignore-line
    pid: "host"
    networks:
      - bingokta
      - metrics
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M
    healthcheck:
      # kics-scan ignore-line
      disable: true

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=bingokta
      - POSTGRES_DB=bingokta
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    cap_drop:
      - ALL
    # kics-scan ignore-line
    cap_add:
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_DAC_OVERRIDE
      - CAP_SETGID
      - CAP_SETUID
    ports:
      - "127.0.0.1:5555:5432"
    security_opt:
      - no-new-privileges:true
    pid: "service:web_app"
    networks:
      - bingokta
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2048M
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - web_app

  jaeger:
    image: jaegertracing/all-in-one:latest
    cap_drop:
      - ALL
    ports:
      - "127.0.0.1:16686:16686"
      - "0.0.0.0:55681:55681"
    environment:
      COLLECTOR_OTLP_ENABLED: true
      COLLECTOR_OTLP_HTTP_HOST_PORT: 55681
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    security_opt:
      - no-new-privileges:true
    pid: "service:web_app"
    networks:
      - metrics
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test:
        - "CMD"
        - "wget --no-verbose --tries=1 http://jaeger:16686 -O /dev/null"
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      - web_app

networks:
  bingokta:
    driver: bridge
  metrics:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password
