name: Gitleaks
on:
  push:

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # v4.1.1
        with:
          fetch-depth: 0
      - name: gitleaks
        uses: gitleaks/gitleaks-action@e6dab246340401bf53eec993b8f05aebe80ac636
        # v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_VERSION: latest
