name: Infrastructure Security Scan
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.rs"
      - "**.md"
      - "Cargo.*"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.rs"
      - "**.md"
      - "Cargo.*"

concurrency:
  group: bingotà-kics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infra-security-scan:
    uses: notdodo/github-actions/.github/workflows/infra-security-scan.yml@cabf073f973a7074895d52d9ba3b59d5b05241ee
    # infra-scan-v0.0.0
