name: Rust CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.*"
      - .github/workflows/rust-ci.yml

concurrency:
  group: bingotà-rust-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-ci:
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@cabf073f973a7074895d52d9ba3b59d5b05241ee
    # rust-ci-v0.0.0
