name: Rust CI

on:
  push:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.*"
      - .github/workflows/rust-ci.yml
  pull_request:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.*"
      - .github/workflows/rust-ci.yml

concurrency:
  group: bingotà-rust-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-ci:
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@rust-ci-v0
