name: Rust

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.*"
      - .github/workflows/rust-ci.yml

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: bingotà-rust-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # v4.1.1
      - name: Cargo cache
        uses: swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        with:
          cache-on-failure: true
          prefix-key: bingokta-build
      - name: Build
        run: cargo build --verbose --release

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # v4.1.1
      - name: Cargo cache
        uses: swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        with:
          cache-on-failure: true
          prefix-key: bingokta-tests
      - name: Run tests
        run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # v4.1.1
      - name: Cargo cache
        uses: swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        with:
          cache-on-failure: true
          cache-all-crates: true
          prefix-key: bingokta-lint
      - name: Install tools
        run: cargo install cargo-make clippy-sarif sarif-fmt
      - name: Run clippy
        run: >
          cargo clippy --all-targets --all-features --message-format=json
          | clippy-sarif
          | tee clippy-results.sarif
          | sarif-fmt
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@b7bf0a3ed3ecfa44160715d7c442788f65f0f923
        with:
          sarif_file: clippy-results.sarif
          wait-for-processing: true
