name: Rust

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.*"
      - .github/workflows/rust-ci.yml

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: bingotà-rust-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # v4.1.1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
