name: Rust CI

on:
  push:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.*"
      - .github/workflows/rust-ci.yml
  pull_request:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.*"
      - .github/workflows/rust-ci.yml

concurrency:
  group: bingotà-rust-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-ci:
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@7676e43de8429ac3e5729edf1ab3e5efc3dcf517
    # rust-ci-v0.0.1
